# -*- coding: utf-8 -*-
"""KPI's in python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fz8X4Caev4y9y4Jy0oc30KGxp4k4Ptab
"""



# To install a Python library, use the `pip install` command.
# For example, to install the pandas library, you would run:
!pip install pandas

# You can replace 'pandas' with the name of any other library you want to install.
# Note the '!' at the beginning, which tells Colab to run this as a shell command.

!pip install matplotlib



import pandas as pd
#1. load Dataset and Display first 10 rows
df = pd.read_csv("/content/dataset.csv", delimiter=';', parse_dates=['Order_Date'])
print(df.head(10))

#2. Calculate total sales and profit per category.
catergory_summary = df.groupby('Category').agg(
    Total_sales = ('Sales', 'sum'),
    Total_profit = ('Profit', 'sum')
).reset_index()
print(catergory_summary)


# 2.Total Sales per Category
category_summary = df.groupby('Category')[['Sales', 'Profit']].sum().reset_index()
print(category_summary)


# 3.customers with Highest Total Orders
customer_orders = df.groupby('Customer_ID')['Order_ID'].count().reset_index()
customer_orders = customer_orders.sort_values(by='Order_ID', ascending=False)
print(customer_orders.head(10))


# 4.Monthly sales Trend
import matplotlib.pyplot as plt
df['Month'] = df['Order_Date'].dt.to_period('M')
monthly_sales = df.groupby('Month')['Sales'].sum()
monthly_sales.plot()
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.xticks(rotation=45)
plt.show()


# 5.products with Average Rating < 3
low_rated_products = df.groupby('Product_ID')['Rating'].mean().reset_index()
low_rated_products = low_rated_products[low_rated_products['Rating'] < 3]
print(low_rated_products)


# 6.Add Profit Margin Column (%)
df['Profit_Margin_%'] = (df['Profit'] / df['Sales']) * 100


# 7.Filter Orders (2024 & South Region)
filtered_df = df[
    (df['Order_Date'].dt.year == 2024) &
    (df['Region'] == 'South')
]
print(filtered_df.head())


# 8.Top 10 Brands by Total Sales
top_brands = df.groupby('Brand')['Sales'].sum().reset_index()
top_brands = top_brands.sort_values(by='Sales', ascending=False).head(10)
print(top_brands)


# 9.Detect Outliers (IQR Method)
Q1 = df['Unit_Price'].quantile(0.25)
Q3 = df['Unit_Price'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['Unit_Price'] < lower_bound) | (df['Unit_Price'] > upper_bound)]
print(outliers)


# 10.Export Summary Report to Excel
summary_report = df.groupby('Category')[['Sales', 'Profit', 'Quantity']].sum().reset_index()
summary_report.to_excel("summary_report.xlsx", index=False)

import pandas as pd
#1. load Dataset and Display first 10 rows
df = pd.read_csv("/content/dataset.csv", delimiter=';', parse_dates=['Order_Date'])
print(df.head(10))

#2. Calculate total sales and profit per category.
catergory_summary = df.groupby('Category').agg(
    Total_sales = ('Sales', 'sum'),
    Total_profit = ('Profit', 'sum')
).reset_index()
print(catergory_summary)

# 3.customers with Highest Total Orders
customer_orders = df.groupby('Customer_ID')['Order_ID'].count().reset_index()
customer_orders = customer_orders.sort_values(by='Order_ID', ascending=False)
print(customer_orders.head(10))

# 4.Monthly sales Trend
import matplotlib.pyplot as plt
df['Month'] = df['Order_Date'].dt.to_period('M')
monthly_sales = df.groupby('Month')['Sales'].sum()
monthly_sales.plot()
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.xticks(rotation=45)
plt.show()

# 5.products with Average Rating < 3
low_rated_products = df.groupby('Product_ID')['Rating'].mean().reset_index()
low_rated_products = low_rated_products[low_rated_products['Rating'] < 3]
print(low_rated_products)

# 6.Add Profit Margin Column (%)
df['Profit_Margin_%'] = (df['Profit'] / df['Sales']) * 100

# 7.Filter Orders (2024 & South Region)
filtered_df = df[
    (df['Order_Date'].dt.year == 2024) &
    (df['Region'] == 'South')]
print(filtered_df.head())

# 8.Top 10 Brands by Total Sales
top_brands = df.groupby('Brand')['Sales'].sum().reset_index()
top_brands = top_brands.sort_values(by='Sales', ascending=False).head(10)
print(top_brands)

# 9.Detect Outliers (IQR Method)
Q1 = df['Unit_Price'].quantile(0.25)
Q3 = df['Unit_Price'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['Unit_Price'] < lower_bound) | (df['Unit_Price'] > upper_bound)]
print(outliers)

# 10.Export Summary Report to Excel
summary_report = df.groupby('Category')[['Sales', 'Profit', 'Quantity']].sum().reset_index()
summary_report.to_excel("summary_report.xlsx", index=False)